feat: 게시판 페이지 레이아웃 구현 (초안)
prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF pull request #73
Opened 2023-09-13 09:16 UTC by wukdddang

## 📌 이슈번호 
- close #47
## 📗 요구 사항과 구현 내용 
- 게시판 페이지의 레이아웃 작업을 수행했습니다.
- 게시글을 클릭하면 라우팅하는 기능까지 추가했습니다.

## 📖 구현 스크린샷 
![ezgif com-video-to-gif (1)](https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/43228743/59111bf9-d190-479b-8fbb-910ccabe9e7c)

## 📖 PR 포인트 & 궁금한 점 
- PR 코드가 300라인보다 초과되었습니다. 죄송합니다.......
- Tab.stories.tsx에서 라우터 관련 에러가 발생해서 <MemoryRouter> 태그로 감싸주었습니다.
- useFilteredArticles 커스텀 훅을 이용해서 **최신의**, **뜨거운**, **구독한** 탭의 Articles만 보여주도록 기능 구현 했습니다.
  - **뜨거운**, **구독한**의 경우 아직 데이터가 없어서 더미 데이터를 넣었습니다.
- 게시글을 불러오는 커스텀 훅 **useArticles**의 **staleTime**은 일단 5초로 했습니다.
- 헤더만 **fixed**로 고정하고 아래 **Articles**만 스크롤 되도록 구현하려 했는데 지금 **Tab, TabItem** 컴포넌트가 강하게 의존하고 있어서 수정이 필요합니다. 이슈 바로 생성해서 리팩토링하겠습니다.
- API를 요청하는 URL과 페이지 라우팅을 위한 URL을 상수로 분리했습니다.

2023-09-13 10:00 UTC, GBAJS754 requested changes

2023-09-13 10:00 UTC, GBAJS754 commented on src/hooks/useArticles.tsx
> +import { useQuery } from '@tanstack/react-query';
이건 hook에 있어야할 이유가 있나요? api폴더 쪽이 더 맞는것같기도...?

2023-09-13 10:10 UTC, wukdddang commented on src/hooks/useArticles.tsx
> +import { useQuery } from '@tanstack/react-query';
아하... 그냥 커스텀 훅으로 분리 하다보니 이렇게 되었네요... 수정하겠습니다!

2023-09-13 10:15 UTC, GBAJS754 commented on src/hooks/useArticles.tsx
> +import { useQuery } from '@tanstack/react-query';
앗 넹ㅋㅋㅋ그렇게 생각한것도 있어요ㅎㅎㅎ잘은 모르겠네용

2023-09-13 12:10 UTC, wukdddang commented on src/hooks/useArticles.tsx
> +import { useQuery } from '@tanstack/react-query';
이 부분은 한번 논의가 필요할 것 같습니다~! 모두 생각이 다를 수 있으니 의견을 나눠보시죠 ㅎㅎ

2023-09-14 08:53 UTC, GBAJS754 approved these changes

2023-09-14 09:00 UTC, GBAJS754 approved these changes

2023-09-14 09:04 UTC, merged